"""
PDF Parsing Script for Skate Canada CSS Documents
Purpose: Extracts specific data from Skate Canada competition PDFs, focusing on Start Order and Results.
Targets: Start Order, Results PDFs generated by CSS software.
Prerequisites: Assumes PDFs follow a consistent format with clear text-based content for extraction.
Author: Bradley Hazelton
Created on: January 02, 2024
Last Updated: January 02, 2024
"""

import pdfplumber
import re
from pathlib import Path
from dateutil.parser import parse

# Create path to test importing start order
pdf_path = Path("D:/SkateInsight/data/start_order/23SS1STAR6WomenGFP2SO.pdf")
# pdf_path = Path("D:/SkateInsight/data/official/23SS1STAR6WomenGFP2OFF.pdf")
# pdf_path = Path(
#    "D:/SkateInsight/data/detail_sheets/23SS1STAR6WomenGFP2DRO.pdf")

date_patterns = [
    # Pattern for written month with optional dash and numeric range
    re.compile(
        r'\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s\d{1,2}-?\s?(?:to|-)?\s?(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)?\s?\d{1,2},?\s\d{4}'),
    # Pattern for purely numeric date ranges
    re.compile(
        r'\b\d{1,2}[-/]\d{1,2}[-/]\d{4}\s?(?:to|-)\s?\d{1,2}[-/]\d{1,2}[-/]\d{4}\b')
]


def find_competition_date_line(text):
    lines = text.strip().split('\n')
    # Limit search to the top 10 lines for the competition date
    search_lines = lines[:10]

    for line in search_lines:
        for pattern in date_patterns:
            if pattern.search(line):
                return line  # Return the matching line as the identified date line

    # If no date line is found in the top 10 lines, return None
    return None


def extract_all_text(pdf_path):
    """
    Extracts all text from a PDF file.

    Parameters:
    - pdf_path (Path): The path to the PDF file.

    Returns:
    - str: A string containing all extracted text from the PDF.
    """
    all_text = ""

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:  # Ensure the page contains text
                all_text += page_text + "\n"

    return all_text


def infer_document_type(text):
    # Simple keyword-based inference for document type
    if "Officials List" in text:
        return "Officials List"
    elif "Starting Order" in text:
        return "Starting Order"
    elif "Result Summary" in text:
        return "Result Summary"
    # Assuming detail sheets contain unique markers like "Element Score", "Deductions", etc.
    elif "Element Score" in text or "Deductions" in text:
        return "Detail Sheets"
    else:
        return "Unknown"


def extract_detail_sheets_header_info(lines, document_type):
    # Extract header info specific to Detail Sheets
    # Adapt based on Detail Sheets' unique structure
    return {
        "Competition Name": lines[0].strip(),
        "Location": lines[2].strip(),
        "Date Range": lines[1].strip(),
        "Event": lines[3].strip(),
        "Document Type": document_type
    }


def extract_event_sheets_header_info(lines, document_type, date_line_index):
    return {
        "Competition Name": " ".join(lines[:date_line_index - 1]).strip(),
        "Location": lines[date_line_index - 1].strip(),
        "Date Range": lines[date_line_index].strip(),
        "Event": lines[date_line_index + 1].strip(),
        "Document Type": document_type
    }


def extract_header_info(text):
    document_type = infer_document_type(text)
    lines = text.strip().split('\n')
    date_line = find_competition_date_line(text)
    date_line_index = lines.index(date_line) if date_line in lines else -1

    if document_type == "Unknown" or date_line_index == -1:
        return {}

    if document_type in ["Officials List", "Starting Order", "Result Summary"]:
        return extract_event_sheets_header_info(lines, document_type, date_line_index)
    elif document_type == "Detail Sheets":
        return extract_detail_sheets_header_info(lines, document_type)


# print((extract_all_text(pdf_path)))
print(extract_header_info(extract_all_text(pdf_path)))

# # Assuming this function is already defined
# extracted_text = extract_all_text(pdf_path)
# parsed_details = parse_competition_details(extracted_text)
# print(parsed_details)
